version: "3.9"
services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development

  app-prod:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
