
FROM python:3.10-slim


WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -m devuser

USER root

COPY requirements.txt .

RUN mkdir -p /app/venv && chmod -R 777 /app/venv


RUN python -m venv /app/venv \
    && . /app/venv/bin/activate \
    && pip install --no-cache-dir -r requirements.txt \
    && pip install --no-cache-dir flask[debug]  

RUN chown -R appuser:appuser /app

USER devuser

COPY . .

EXPOSE 5000

ENV PATH="/app/venv/bin:$PATH"

CMD ["venv/bin/python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5000"]
